version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:4350"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 10gb
